Update modal.md
facebook/react-native-website pull request #2175
Opened 2020-08-25 13:42 UTC by mojvan

Hello everyone...
Please edit onRequestClose prop and add setModalVisible(!modalVisible); to function component and add this.setModalVisible(!modalVisible); to class component.
Thus the modal has been closed with hardware back button practically...
Thanks

2020-08-25 14:02 UTC, mojvan reviewed
Hello everyone...
Please edit onRequestClose prop and add setModalVisible(!modalVisible); to function component and add this.setModalVisible(!modalVisible); to class component.
Thus the modal has been closed with hardware back button practically...
Thanks

2020-08-26 06:59 UTC, Simek requested changes
Thank you for fixing that part of example! 👍 

Unfortunately I'm not able to commit to this PR to correct the whitespaces in the class component example. Can you fix that?

2020-08-26 11:30 UTC, mojvan commented
 I fixed it...از گوشی هوشمند Samsung Galaxy ارسال شده است.
-------- پیام اصلی --------از: Bartosz Kaszubowski <notifications@github.com> تاریخ: ۲۰۲۰/۸/۲۶  ۱۱:۲۹  (GMT+03:30) گیرنده: facebook/react-native-website <react-native-website@noreply.github.com> گیرنده کپی: Mojtaba Vandaei <mojvan.mojvan@gmail.com>, Manual <manual@noreply.github.com> موضوع Re: [facebook/react-native-website] Update modal.md (#2175) 

@Simek requested changes on this pull request.



Thank you for fixing that part of example! 👍

Unfortunately I'm not able to commit to this PR to correct the whitespaces in the class component example. Can you fix that?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/facebook/react-native-website/pull/2175#pullrequestreview-475202677",

"url": "https://github.com/facebook/react-native-website/pull/2175#pullrequestreview-475202677",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

2020-08-26 13:44 UTC, mojvan reviewed
Sorry
I made a mistake and corrected it again...

2020-08-26 14:10 UTC, Simek approved these changes
@mojvan Not a problem, thank you for fixing the example and working on the review updates! 👍

2020-08-26 14:11 UTC, merged