Update getting-started.md
facebook/react-native-website pull request #2218
Opened 2020-09-21 00:06 UTC by juniorjblp

Added topic indicating the installation of react-native-cli for unexpected users

2020-09-21 18:47 UTC, Simek requested changes
Hi @juniorjblp, the global CLI installation is no longer required or recommended (you have also choose the legacy package):
* https://github.com/react-native-community/cli#about

Currently most of the command can be executed with `npx` (without installation):
* https://github.com/react-native-community/cli#creating-a-new-react-native-project

2020-09-21 18:51 UTC, Simek commented on docs/getting-started.md
> +sudo npm install -g react-native-cli
You have added the section in the Android & Windows guide, without a WSL there is no Bash (and `sudo`) on Windows.

2020-09-21 18:51 UTC, Simek commented on docs/getting-started.md
> +First, you will need to start Metro, the JavaScript bundler that ships with React Native. Metro "takes in an entry file and various options, and returns a single JavaScript file that includes all you
This change is unnecessary.

2020-09-29 04:32 UTC, cpojer commented
Closing this as I don't think we need this change?

2020-09-29 04:32 UTC, closed without merging