:sparkles: :whale: Docker for React Native Website
facebook/react-native-website pull request #2242
Opened 2020-10-03 08:08 UTC by VISWESWARAN1998

Added Dockerfile for easy deployment.

Thanks and Regards,
Visweswaran N

2020-10-03 08:20 UTC, VISWESWARAN1998 commented
I have considered adding a docker file because anyone with docker can easily deploy and test the website without any tools and installation procedures.

2020-10-07 18:41 UTC, rachelnabors commented
That seems really cool, but I'm not sure that's a use case we're ready to support. Could you submit an update to the Repo's README to explain how to use as well?

2020-10-08 04:03 UTC, VISWESWARAN1998 commented
http://react-native-website.visweswaran.com is deployed using docker for your reference.

2020-10-29 13:03 UTC, Simek requested changes
Hey @VISWESWARAN1998, thank you for proposing this change.

Can you make sure that the `Dockerfile` is correct after the website has been migrated to the new framework? And please, can you remove the comment in this file?

Also it is not clear enough for me what are the benefits of offering and using the website with Docker? Can you elaborate on that?

2020-11-17 12:30 UTC, Simek commented on Dockerfile
> +RUN npm install
It is possible that `npm` command won't be working correctly after the introduction of Yarn workspaces in the repository. Can you test this out against current `master`?

2020-12-03 13:40 UTC, rachelnabors commented
Going to close because Docker support seems like it is out of scope for this project

2020-12-03 13:40 UTC, closed without merging