Fix Typescript hyperlink in testing-overview
facebook/react-native-website pull request #2286
Opened 2020-10-30 03:26 UTC by cgathergood

https://reactnative.dev/docs/testing-overview/#static-analysis

Clicking on the `Typescript` hyperlink will navigate to `https://reactnative.dev/docs/testing-overview/typescript` which does not exist.

This update fixes the link in the docs to `https://www.typescriptlang.org/`

2020-10-30 09:49 UTC, Simek requested changes
Hi @cgathergood, thank you for spotting and reporting this out. 

But this link should lead to https://reactnative.dev/docs/typescript/ not the TypeScript website, can you update the PR?

2020-10-30 21:47 UTC, cgathergood commented
Thanks @Simek updated the link. What do you mean by updating the next doc file? Thanks

2020-10-31 13:26 UTC, Simek commented
> Thanks @Simek updated the link. What do you mean by updating the next doc file? Thanks

@cgathergood The current docs. You can read more about versioning system on the website in Readme: https://github.com/facebook/react-native-website#documentation-sources

But after the bit of research it looks like the links are correct and any changes to them are unnecessary. We are experiencing the trailing slash issue on the deployed site which break links only in certain situations and it need to be addressed on the deployment side. For the details please check out #2291.

2020-10-31 14:12 UTC, Simek commented
Closing in favor of #2291.

2020-10-31 14:12 UTC, closed without merging