Chaged from 'background' to 'backgroundColor'
facebook/react-native-website pull request #2299
Opened 2020-11-01 05:25 UTC by PhoenixCreation

Changes:
```diff
- background: "lightGrey"
+ backgroundColor: "lightgrey"
```

In example of LayoutAnimation stylesheet for 'title' contains 'background' property.
It throws error as it should be 'backgroundColor'.
also value of the same is 'lightGrey' which is not supported. It should be 'lightgrey'.

2020-11-02 14:18 UTC, Simek requested changes
Nice catch, thank you! Can you also update the main (`next`) docs at https://github.com/facebook/react-native-website/blob/master/docs/layoutanimation.md?

2020-11-02 14:31 UTC, PhoenixCreation commented
@Simek Yeah. Sure. But I will do it tomorrow. Thanks you.

2020-11-03 04:42 UTC, PhoenixCreation commented
I have updated at main docs. Let me know if there is any issue with this.

2020-11-03 09:17 UTC, Simek approved these changes
LGTM, thank you for fixing this issue! 👍

2020-11-03 09:18 UTC, merged