feat: add `getRecommendedTimeoutMillis` section on accessibilityInfo
facebook/react-native-website pull request #2581
Opened 2021-04-07 02:10 UTC by grgr-dkrk

This PR adds documentation for the features implemented in https://github.com/facebook/react-native/pull/31063.

2021-04-07 07:41 UTC, Simek requested changes
Hi @grgr-dkrk, thank you for the update! 👍 

Please retain the alphabetic order of methods on the page, use the `required` tag and table format as seen on, for example, Alert page:
* https://reactnative.dev/docs/next/alert

2021-04-07 08:08 UTC, grgr-dkrk commented
@Simek Thanks!

2021-04-07 08:20 UTC, Simek commented
Thank you for the update, but the methods alphabetical order is still not correct:
<img width="200" alt="Screenshot 2021-04-07 101838" src="https://user-images.githubusercontent.com/719641/113834122-c1584280-978a-11eb-8ce8-d7db071350ca.png">

2021-04-07 08:42 UTC, Simek commented on docs/accessibilityinfo.md
> +On Android, This value is set in "Time to take action (Accessibility timeout)" of "Accessibility" settings.
Since it's Android only method, can we skip the "On Android" in this sentence?

2021-04-07 08:44 UTC, Simek commented on docs/accessibilityinfo.md
> +| originalTimeout <div class="label basic required">Required</div> | number | The timeout to return if "Time to take action (Accessibility timeout)" is not set. Specify in milliseconds. |
```suggestion
| originalTimeout <div class="label basic required">Required</div> | number | The timeout to return if "Accessibility timeout" is not set. Specify in milliseconds. |
```

2021-04-07 09:13 UTC, Simek approved these changes
LGTM, thank so much you for all the review updates! 🙂

2021-04-07 09:13 UTC, merged

2021-04-08 12:33 UTC, amarlette commented
Thank you @grgr-dkrk for fixing and documenting this issue!