Update native-modules-android.md
facebook/react-native-website pull request #2791
Opened 2021-09-24 14:13 UTC by simonbrunou

Those two methods are missing in the documentation and an exception is sent if they are not in the code.

2021-09-24 14:16 UTC, simonbrunou commented
Signed CLA.

2021-09-29 11:30 UTC, mocktarissa approved these changes

2021-09-29 11:53 UTC, satya164 reviewed
Can you post what exception you got and share a link to the native module which implemented this?

2021-09-29 12:12 UTC, simonbrunou commented
When omitting `addListener`, this is the exception:
```bash
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
```

When omitting `removeListeners`, this is the exception:
```bash
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

I cannot share a link to the native module which implemented this when I was confronted with the problem as it is proprietary source code. However I can put together a file that implements it quickly, if needed.

2021-10-04 17:46 UTC, rubennorte commented on docs/native-modules-android.md
> + // Keep: Required for RN built in Event Emitter Calls.
I think it's a good idea to add these required methods in the examples, but I'd modify the comment to be more useful for people reading it.

In iOS we have the same (https://reactnative.dev/docs/native-modules-ios#sending-events-to-javascript):
```
@implementation CalendarManager
{
  bool hasListeners;
}

// Will be called when this module's first listener is added.
-(void)startObserving {
    hasListeners = YES;
    // Set up any upstream listeners or background tasks as necessary
}

// Will be called when this module's last listener is removed, or on dealloc.
-(void)stopObserving {
    hasListeners = NO;
    // Remove upstream listeners, stop unnecessary background tasks
}

- (void)calendarEventReminderReceived:(NSNotification *)notification
{
  NSString *eventName = notification.userInfo[@"name"];
  if (hasListeners) { // Only send events if anyone is listening
    [self sendEventWithName:@"EventReminder" body:@{@"name": eventName}];
  }
}
```

2021-10-04 17:48 UTC, rubennorte commented
Thanks @simonbrunou for improving our docs! This was definitely incomplete without the examples that you added. Can you please address my comment so we can merge it? Thanks!

2021-10-04 19:30 UTC, simonbrunou commented
> Thanks @simonbrunou for improving our docs! This was definitely incomplete without the examples that you added. Can you please address my comment so we can merge it? Thanks!

I think it's done, however I'm not familiar with GitHub's interface so correct me if I did something wrong.

2021-10-05 11:12 UTC, Simek requested changes
Hi @simonbrunou, thank you for bringing this topic up! 👍 

Since the change landed in `0.65` release (https://github.com/facebook/react-native/commit/114be1d2170bae2d29da749c07b45acf931e51e2), please update also versioned docs for `0.65` and `0.66` besides the `next` file:
* https://github.com/facebook/react-native-website#versioned-docs

2021-10-05 11:17 UTC, simonbengtsson commented
I assume the tag should have been on @simonbrunou @Simek

2021-10-05 11:26 UTC, Simek commented
Ugh, yup! Sorry about that! I should not trust the GitHub mention autocomplete. 😅

2021-10-05 11:27 UTC, simonbengtsson commented
Haha 😅

2021-10-05 11:30 UTC, Simek commented
@simonbengtsson I will mark this conversation as off-topic now, to reduce the noise in the issue. Thank you so much for the comment and your forbearance! 🙂

2021-10-05 12:40 UTC, simonbrunou commented
I rebased on main and added the changes to the documentation.

2021-10-05 14:45 UTC, Simek reviewed
It looks like you did not force push after rebase, which leads to malformed PR, please fix that. 😉

2021-10-05 15:10 UTC, simonbrunou commented
It should be good now.

2021-10-05 15:18 UTC, Simek approved these changes
Thank you for the updates! 👍 

From the technical standpoint it LGTM, but let's wait with the merge for the @rubennorte approval on the wording/description changes. 🙂

2021-10-05 15:24 UTC, rubennorte commented
I think we can still improve the comment. I don't think the current one is useful to tell people what this is for, only that's required. We could say something like what we say on iOS.

So instead of:
```
 // Keep: Required for RN built in Event Emitter Calls.
```

We could use something like:
```
@ReactMethod
public void addListener(String eventName) {
  // Set up any upstream listeners or background tasks as necessary
}

@ReactMethod
public void removeListeners(Integer count) {
  // Remove upstream listeners, stop unnecessary background tasks
}
```

@simonbrunou could you please make these changes? Sorry for the back and forth.

2021-10-05 16:44 UTC, merged

2021-10-05 16:44 UTC, rubennorte commented
Thanks for improving our website, @simonbrunou!