Adding a command
facebook/react-native-website pull request #2921
Opened 2022-01-09 06:43 UTC by DiegoDialga

While starting the server , I found 'docusaurus' is not recognized as an internal or external command, operable program or batch file .  It took me some time to find the solution and found this command on stackoverflow. If included here, the command might help the user in dealing with such problems and it will save the user's time.

2022-01-10 11:54 UTC, Simek requested changes
Hello @DiegoDialga,

Can you provide the link to the Stack Overflow post you have mentioned? Also the information what exactly error you were receiving without the upgrade would be helpful.

Generally, running the added command will upgrade the Docusaurus version used on the website to the latest release, sice we are using `^` in a semver, and this might lead to other, unexpected compatibility issues and problems.

Also, did you run the `yarn` command in the `website` directory, as stated in the guide, before running `yarn start` in `website` folder?

2022-01-10 23:51 UTC, DiegoDialga commented
Hi @Simek ,
This is the link for the stackoverflow post "https://stackoverflow.com/questions/68632133/how-to-solve-docusaurus-yarn-start-error?noredirect=1&lq=1". I think you are right, I might not have run the yarn command before starting it.
Then I guess adding 'run' before yarn might help otherwise it is not clearly specifying that the user has to run the yarn command before yarn start

2022-01-11 00:10 UTC, Simek commented
Thank you for clarifying! 👍 I'm happy that I was able to help!

> Then I guess adding 'run' before yarn might help otherwise it is not clearly specifying that the user has to run the yarn command before yarn start

Running `yarn` step is listed just few lines above, in the Readme file, in the "Installation" section:
* https://github.com/facebook/react-native-website/blob/main/README.md#installation

If you think that the steps can be improved, please make an update to this PR.

2022-01-11 10:37 UTC, Simek approved these changes
LGTM, thank you for the updates! 👍

2022-01-11 10:38 UTC, merged