Add function based components example for Flat list optimisation
facebook/react-native-website pull request #2955
Opened 2022-02-03 19:18 UTC by DibyajyotiMishra

A minor update to the docs addressing the issue : https://github.com/facebook/react-native-website/issues/2880

2022-02-03 19:50 UTC, Simek requested changes
Hello @DibyajyotiMishra, thank you for working on the fix for this issue! 👍 

Can you use the `Tabs` components instead of paragraphs to stay more in line with how the Class and Functional components examples are handled across website?

You can find the example use on many Components and APIs page, for example:
* https://github.com/facebook/react-native-website/blob/main/docs/activityindicator.md?plain=1

2022-02-04 03:48 UTC, DibyajyotiMishra commented
> Hello @DibyajyotiMishra, thank you for working on the fix for this issue! 👍
> 
> Can you use the `Tabs` components instead of paragraphs to stay more in line with how the Class and Functional components examples are handled across website?
> 
> You can find the example use on many Components and APIs page, for example:
> 
> * https://github.com/facebook/react-native-website/blob/main/docs/activityindicator.md?plain=1

Sure. I will do that.

2022-02-04 09:59 UTC, DibyajyotiMishra commented
> > Hello @DibyajyotiMishra, thank you for working on the fix for this issue! 👍
> > Can you use the `Tabs` components instead of paragraphs to stay more in line with how the Class and Functional components examples are handled across website?
> > You can find the example use on many Components and APIs page, for example:
> > 
> > * https://github.com/facebook/react-native-website/blob/main/docs/activityindicator.md?plain=1
> 
> Sure. I will do that.

Hi @Simek, are the commits rightly done? Can I expect a merge? Just asking. Never mind. :)

2022-02-04 10:01 UTC, Simek commented
Hi @DibyajyotiMishra, I was going to check this branch out locally to fix the Lint issues, if you can do that for me it would be nice. This is the last thing blocking this PR from merge. :)

2022-02-04 10:09 UTC, DibyajyotiMishra commented
> Hi @DibyajyotiMishra, I was going to check this branch out locally to fix the Lint issues, if you can do that for me it would be nice. This is the last thing blocking this PR from merge. :)

Sure. I have done it. Raising a PR.

2022-02-04 10:40 UTC, DibyajyotiMishra commented
> Hi @DibyajyotiMishra, I was going to check this branch out locally to fix the Lint issues, if you can do that for me it would be nice. This is the last thing blocking this PR from merge. :)

Hi @Simek , I have fixed all the linting issues. Can you spare some time and may be merge it? 😬

2022-02-04 10:41 UTC, Simek commented on docs/optimizing-flatlist-configuration.md
> +)
```suggestion
return (
  // ...

  <FlatList data={items} renderItem={renderItem} />;
  // ...
);
```
Thanks for the lint fixes! :+1: Let's mis the code formatting too.

2022-02-04 10:49 UTC, Simek approved these changes
Thank you for the updates, great work, let's ship it! 🚀 

Unfortunately Prettier changes might be hard to apply manually, but if you check out repo locally there is a command for that and auto lint also runs on changed files post-commit via hooks, which makes linting files way less annoying.

2022-02-04 10:50 UTC, merged

2022-02-04 10:55 UTC, DibyajyotiMishra commented
> Thank you for the updates, great work, let's ship it! 🚀
> 
> Unfortunately Prettier changes might be hard to apply manually, but if you check out repo locally there is a command for that and auto lint also runs on changed files post-commit via hooks, which makes linting files way less annoying.

Thanks a lot. I didn’t check the script. I forgot actually. I was in a hurry to fix the linting so I did all of them manually. 😅

2022-07-29 13:25 UTC, DomiR commented
Sorry, but how is this optimizing the Performance?

We replace: 
```
<FlatList renderItem={() => {}} />
```

with 
```
const f = () => {}
<FlatList renderItem={f} />
```

I don't see how this can help performance, as f will be different each time... it should be wrapped in useCallback.