Adding Explain Like I'm 5 video to the home page
facebook/react-native-website pull request #2971
Opened 2022-02-16 22:26 UTC by dmitryvinn

# Summary

Here at Meta Open Source, we've been creating short-form videos to explain Meta OSS projects in the simplest terms possible. We started embedding these videos into project pages as you can see in [Docusaurus home page](https://docusaurus.io/), [Jest](https://jestjs.io/), [Litho](https://fblitho.com/), [Hydra](https://hydra.cc/), etc..

# Test Plan
Here is a screenshot in how it looks:
![image](https://user-images.githubusercontent.com/12485205/154367846-c3fc57a4-b419-4015-be79-994624e00598.png)

2022-02-17 11:00 UTC, Simek reviewed
Hello @dmitryvinn, thank you for pushing this update. 👍 

Generally I think it's a good idea to add the 5 minutes video to the homepage. IIRC there were discussions earlier, if we can update or replace Talks video/section (it's a bit outdate), so it might be a good opportunity to do that. 

However, if we decide to leave two sections, I would have a few design related suggestions - it would be nice to stick to alternating background color of sections and separate 5min video with talks this way, also the copy on the newly added part seems a bit to long now, we should aim to fit the description in way, which do not extend the video section container.

Let's ask others about their opinion.

2022-02-17 16:27 UTC, dmitryvinn commented
@Simek  absolutely - I will go with whatever approach you and the team decides to take

2022-02-21 21:39 UTC, dmitryvinn commented
@Simek I don't see any other comments on this PR - I think replacing the video might be the easiest thing to do, so if you agree, I can update the PR with that design

2022-02-22 19:49 UTC, lunaleaps requested changes

2022-02-22 19:49 UTC, lunaleaps commented on website/src/pages/index.js
> +other content about Meta Open Source projects on their <a href="https://www.youtube.com/channel/UCCQY962PmHabTjaHv2wJzfQ">YouTube Channel</a>.
I think this is odd to add -- I don't think coming to the React Native homepage folks are generally looking for other Meta Open Source projects. Can we remove the text "You can also find other content... You can follow the latest Meta OSS news.. " and just keep the twitter follow button?

2022-02-22 19:49 UTC, lunaleaps commented on website/src/pages/index.js
> +other content about Meta Open Source projects on their <a href="https://www.youtube.com/channel/UCCQY962PmHabTjaHv2wJzfQ">YouTube Channel</a>.
As well as re-ordering so the React Native talk video is on top as mentioned earlier?

2022-02-24 00:14 UTC, dmitryvinn commented
What do you think about this version?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12485205/155432586-e1121e2f-de87-403d-aea6-e3b488804502.png">

2022-02-24 00:18 UTC, lunaleaps approved these changes
Thanks @dmitryvinn! Looks good to me!

2022-02-24 00:20 UTC, lunaleaps commented
cc @Simek if you had more design comments? Maybe those can be addressed in a separate change? As well as updating the 2019 talk with a more current video

2022-02-24 09:45 UTC, Simek approved these changes
I would like to experiment with the arrangement a bit in the future, but this can be addressed in separate PR as well as talk video replacement as you suggested. 

After latest updates, the current iteration LGTM, I think that we can ship it. :)

2022-02-24 15:17 UTC, merged