changed android_hyphenation to version 0.67.3
facebook/react-native-website pull request #2982
Opened 2022-02-28 11:17 UTC by zegermouw

This PR changes the documentation of the android_hyphenation property to the new changes of version 0.67.3 as stated in this changelog: 
https://github.com/facebook/react-native/blob/main/CHANGELOG.md#android-specific-3
This PR corresponds to the following issue:
https://github.com/facebook/react-native/issues/33104

2022-03-08 12:52 UTC, Simek requested changes
Hello @zegermouw, thank you for the correction! 👍 

Can you also update the `0.67` docs files located in `/website/versioned_docs/version-0.67`? I have tried to backport the changes myself, but it looks like you did not allow the changes to the branch via maintainers.

2022-03-08 14:45 UTC, zegermouw reviewed
Check!

2022-03-08 15:12 UTC, Simek approved these changes
Thank for the update, Let's ship it! 🚀

2022-03-08 15:12 UTC, merged

2022-03-08 16:15 UTC, Simek commented
Oops, after a check in the RN code it looks like we are missing `normal` enum option in all of the docs versions. 😅  

Would you like to address this via PR @zegermouw? Editing current and versioned files for `0.67` should be enough, but you can backport this further, if you want. It is fine, if you are not interested in this, just let me know, so I can work on this.

2022-03-09 14:53 UTC, zegermouw commented
I'm on it!

2022-03-09 19:06 UTC, zegermouw commented
I added a [PR](../3002) for this!