React native Kotlin examples
facebook/react-native-website pull request #3030
Opened 2022-03-24 23:39 UTC by alanjhughes

2022-03-25 05:53 UTC, alanjhughes commented
@cortinico @ShikaSD @mdvacca

2022-03-25 10:19 UTC, Simek requested changes
Hello @alanjhughes, thank you for contributing to the Kotlin examples conversion project! 👍 

I did not check the content after changes, but I have spotted that you have edited the last versioned docs only. To preserve the changes for the future versions and include the in any other new generated ones, you need to edit the file inside `docs` folder. For mor information see:
* https://github.com/facebook/react-native-website#documentation-sources

2022-03-25 11:42 UTC, alanjhughes commented
Hi @Simek sorry about that. First open-source contribution. I've changed it now

2022-03-25 11:57 UTC, cortinico reviewed
Great stuff 👍  Thank you for tackling this. Left several comments

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +The first step is to create the (CalendarModule.java or CalendarModule.kt) Java/Kotlin file inside `android/app/src/main/java/com/your-app-name/` folder. This Java/Kotlin file will contain your nativ
```suggestion
The first step is to create the (`CalendarModule.java` or `CalendarModule.kt`) Java/Kotlin file inside `android/app/src/main/java/com/your-app-name/` folder. This Java/Kotlin file will contain your native module Java/Kotlin class.
```

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +The first step is to create the (CalendarModule.java or CalendarModule.kt) Java/Kotlin file inside `android/app/src/main/java/com/your-app-name/` folder. This Java/Kotlin file will contain your nativ
Plus here there could be confusion on the folder as there is Java in this path `android/app/src/main/java/com/your-app-name/`.

Maybe adding a `(the folder is the same for both for either Kotlin of Java)` would help clarify.

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
>  ### Synchronous Methods
There is a snipped here missing.

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +    }
Maybe simplify to:
```
listOf(CalendarModule(reactContext)).toMutableList()
```

or use 

```
 = mutableListOf().apply { add(CalendarModule(reactContext)) }
```

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +To register the `CalendarModule` package, you must add `MyAppPackage` to the list of packages returned in ReactNativeHost's `getPackages()` method. Open up your `MainApplication.java` or `MainApplica
As above, let's stick to a single source folder. 
Given that `android/app/src/main/java/` works for both Java and Kotlin, I'd stick to that.

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +}
```suggestion
override fun getPackages(): List<ReactPackage> = PackageList(this).packages.apply {
    // Packages that cannot be autolinked yet can be added manually here, for example:
    // add(new MyReactNativePackage());
    add(MyAppPackage())
}
```

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
>  | boolean       | boolean    |
Kotlin doesn't primitive types (e.g. `boolean`). 

Maybe `boolean` and `double` in this table should be exported to a separate Java only table?

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
>  | boolean       | boolean    |
Same for `int` and `float` below

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +    sdf.parse(startDate)?.let {
Previously there was a `try` there that you removed. I'm assuming it was needed to catch parsing exceptions therefore should be kept here as well (maybe with a `runCatching` or something more idiomatic).

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +}
```suggestion
override fun getConstants(): MutableMap<String, Any> = hashMapOf(
    "DEFAULT_EVENT_NAME" to "New Event"
)
```

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +      callback.invoke(null, eventId)
Nothing to address here, but that's so kotlin sad and unfriendly 😅  @ShikaSD @mdvacca

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +@ReactMethod
That's wrongly aligned? All the code should be formatted with 
https://facebookincubator.github.io/ktfmt/

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +            currentActivity!!.startActivityForResult(chooserIntent, IMAGE_PICKER_REQUEST)
Please assign `currentActivity` to a val on line 1036.
As you're null checking at line 1037 you'll be smartcasted to a non-null `Activity` here and you don't need the double bang.

2022-03-25 11:57 UTC, cortinico commented on docs/native-modules-android.md
> +            val galleryIntent = Intent(Intent.ACTION_PICK)
```suggestion
            val galleryIntent = Intent(Intent.ACTION_PICK).apply {
                type = "image/\*"
            }
```

2022-03-25 11:58 UTC, cortinico commented
> To preserve the changes for the future versions and include the in any other new generated ones, you need to edit the file inside `docs` folder. For mor information see:

Small nit, before you re-apply all the changes, let's agree on the valid code first so you won't have to re-apply every small change over and over :)

2022-03-25 12:42 UTC, alanjhughes commented
Hi @cortinico sorry, I had resubmitted before I saw your most recent comment. I'll wait to discuss any further changes with you before pushing again

2022-03-25 13:53 UTC, cortinico reviewed
Just a small nit. Also have you tested the code I suggested? Asking as I'm writing it in the browser and it could be wrong

2022-03-25 13:53 UTC, cortinico commented on docs/native-modules-android.md
> +        val currentActivity = currentActivity
```suggestion
        val activity = currentActivity
```

Don't name shadow otherwise the IDE will warn users here.

2022-03-25 14:15 UTC, alanjhughes commented
No problem, I'll make that change now. Yes, I'm rebuilding and running the app as I make the changes. All working fine.

2022-03-25 14:35 UTC, Simek commented on docs/native-modules-android.md
> +
```suggestion
```

Small whitespace cleanup suggestion.

2022-03-25 14:37 UTC, Simek commented on docs/native-modules-android.md
> +}
Hmm, it looks like there is an additional closing bracket (`}`), which leads to the error, when trying to format the code in `ktfmt` tool.

2022-03-25 14:44 UTC, alanjhughes commented
@Simek sorry, missed that one

2022-03-25 14:54 UTC, Simek commented on docs/native-modules-android.md
> +}
One more thing. The Java example includes the imports at the beginning of code, do we need those in Kotlin file too?

2022-03-25 15:26 UTC, Simek approved these changes
Thank you for all the updates and work you have put into this @alanjhughes! 👍 

I will leave the PR for @cortinico to approve and finally merge it in.

2022-03-25 16:07 UTC, alanjhughes commented
Great, thanks @Simek 👍

2022-03-26 18:30 UTC, cortinico approved these changes

2022-03-26 18:30 UTC, merged

2022-03-26 18:31 UTC, cortinico commented
Great work @alanjhughes 🙏 Thank you for taking a stance at this

2022-03-26 19:39 UTC, alanjhughes commented
Thanks @cortinico 👍 I will try to do some more