added kotlin code into "new-architecture-app-renderer-android" documentation
facebook/react-native-website pull request #3303
Opened 2022-09-07 08:58 UTC by dakshbhardwaj

This Pr adds `kotlin`  code to the `new-architecture-app-renderer-android` docs
Reference: #3018

2022-09-07 14:15 UTC, cortinico requested changes
Thanks for sending this over @dakshbhardwaj
There are several changes to apply + I believe you haven't tested the code as it won't compile as it is now. Can I ask you to try your snippets? Also have you used ktfmt for formatting them?

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +  private val mReactNativeHost: ReactNativeHost =
```suggestion
  private val reactNativeHost: ReactNativeHost =
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +        @get:Nullable
Nullable is not needed in Kotlin.

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +                    jsContext: JavaScriptContextHolder?
```suggestion
                    reactApplicationContext: ReactApplicationContext,
                    jsContext: JavaScriptContextHolder
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +              object : JSIModulePackage() {
I believe this can be converted to a SAM using `JSIModulePackage { ... }`

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +                  specs.add(
```suggestion
                ): List<JSIModuleSpec> = listOf(
```

Let's collapse this and use functional notation here.

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +                      })
I'd suggest you take a look at this class:
https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/defaults/DefaultJSIModulePackage.kt

As it's similar to what you're doing here and it's a bit more idiomatic 👍 Feel free to ask questions if you have any.

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +    }
```suggestion
   override fun createRootView(): ReactRootView =
      ReactRootView(getContext()).apply { setIsFabric(fabricEnabled) }
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +  protected fun createReactActivityDelegate(): ReactActivityDelegate {
I believe you miss a `override` modifier here.

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +    SimpleViewManager<MyNativeView?>(), RNTMyNativeViewManagerInterface<MyNativeView?> {
```suggestion
    SimpleViewManager<MyNativeView>(), RNTMyNativeViewManagerInterface<MyNativeView> {
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +  private val mDelegate: ViewManagerDelegate<MyNativeView>
```suggestion
  private val delegate: ViewManagerDelegate<MyNativeView>
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +    protected get() = mDelegate
This should be removed

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +  }
```suggestion
  protected fun createViewInstance(reactContext: ThemedReactContext) = 
    MyNativeView(reactContext)
```

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +      get() = Companion.field
This can go

2022-09-07 14:15 UTC, cortinico commented on docs/new-architecture-app-renderer-android.md
> +          } // Your ViewManager is returned here.
This is wrong. Have you used some auto-convertion feature?

2022-09-07 14:34 UTC, dakshbhardwaj commented
> Thanks for sending this over @dakshbhardwaj There are several changes to apply + I believe you haven't tested the code as it won't compile as it is now. Can I ask you to try your snippets? Also, have you used ktfmt for formatting them?

Hi @cortinico I am closing this pr as I haven't tested the code yet.

2022-09-07 14:34 UTC, closed without merging

2022-09-07 21:12 UTC, cortinico commented
> Hi @cortinico I am closing this pr as I haven't tested the code yet.

Don't worry 👍 I assume you're still working on it right?

2022-10-05 10:18 UTC, cortinico commented
This is not needed anymore as the page has been removed 👍