added documentation for `aria-valuemax` `aria-valuemin` `aria-valuenow` `aria-valuetext`
facebook/react-native-website pull request #3318
Opened 2022-09-12 08:35 UTC by dakshbhardwaj

This PR adds documentation for `aria-valuemax`, `aria-valuemin`, `aria-valuenow`,`aria-valuetext` props.

Related to commit https://github.com/facebook/react-native/commit/e8739e962de3398bc7e42675b1d87ab35993f705

and issue https://github.com/facebook/react-native/issues/34424

2022-09-21 11:40 UTC, Simek commented on docs/touchablewithoutfeedback.md
> +It Represents the maximum value for range-based components, such as sliders and progress bars. Has precedence over the `accessibilityValue.max` prop.
```suggestion
Represents the maximum value for range-based components, such as sliders and progress bars. Has precedence over the `max` value in the `accessibilityValue` prop.
```

Please remove "It" at the beginning of each description, ensure that case is correct and rephrase the precedence sentence as seen above in other entries added.

2022-09-21 11:40 UTC, Simek requested changes
See the comment.

2022-09-23 06:29 UTC, dakshbhardwaj commented
> See the comment.

Thanks for the review @Simek. i have pushed down the changes

2022-09-23 07:04 UTC, Simek commented
Can you resolve the conflicts created after the merge of other PRs?

2022-09-23 08:19 UTC, dakshbhardwaj commented
> Can you resolve the conflicts created after the merge of other PRs?

@Simek i have resolved the conflicts

2022-09-23 09:03 UTC, Simek approved these changes
LGTM, thank you for those additions! 🙏

2022-09-23 09:03 UTC, merged