chore: clean up new arch docs
facebook/react-native-website pull request #3332
Opened 2022-09-20 16:54 UTC by kelset

I was re-reading the whole set of new arch docs and I noticed a few things that needed to be fixed, so here's the PR :)
It's all fairly minor stuff, typos and things like those.

2022-09-20 17:50 UTC, cortinico commented on docs/new-architecture-library-intro.md
> -## Preparing your JavaScript Codebase for the new React Native Renderer (Fabric)
I'd revert this 🤔

2022-09-21 10:43 UTC, cipolleschi requested changes
Let's revert the line highlighted by Nico and then we can merge this. Thank you for taking care of this!

2022-09-22 09:41 UTC, kelset commented on docs/new-architecture-library-intro.md
> -## Preparing your JavaScript Codebase for the new React Native Renderer (Fabric)
sounds good - will take care of it now

2022-09-22 10:31 UTC, cortinico approved these changes

2022-09-22 10:32 UTC, merged